
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.FileChooserButton FileChooserButton;
	private global::Gtk.Alignment alignment1;
	private global::Gtk.HButtonBox hbuttonbox1;
	private global::Gtk.Button RunMessagesButton;
	private global::Gtk.Button RunHTMLDebugButton;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView originalTextView;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TreeView TreeView;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.FileChooserButton = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.FileChooserButton.Name = "FileChooserButton";
		this.FileChooserButton.ShowHidden = true;
		this.hbox1.Add (this.FileChooserButton);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.FileChooserButton]));
		w1.Position = 0;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		// Container child alignment1.Gtk.Container+ContainerChild
		this.hbuttonbox1 = new global::Gtk.HButtonBox ();
		this.hbuttonbox1.Name = "hbuttonbox1";
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.RunMessagesButton = new global::Gtk.Button ();
		this.RunMessagesButton.CanFocus = true;
		this.RunMessagesButton.Name = "RunMessagesButton";
		this.RunMessagesButton.UseUnderline = true;
		this.RunMessagesButton.Label = global::Mono.Unix.Catalog.GetString ("Run Messages");
		this.hbuttonbox1.Add (this.RunMessagesButton);
		global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.RunMessagesButton]));
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.RunHTMLDebugButton = new global::Gtk.Button ();
		this.RunHTMLDebugButton.CanFocus = true;
		this.RunHTMLDebugButton.Name = "RunHTMLDebugButton";
		this.RunHTMLDebugButton.UseUnderline = true;
		this.RunHTMLDebugButton.Label = global::Mono.Unix.Catalog.GetString ("Run HTML Debug");
		this.hbuttonbox1.Add (this.RunHTMLDebugButton);
		global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.RunHTMLDebugButton]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.alignment1.Add (this.hbuttonbox1);
		this.vbox1.Add (this.alignment1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.originalTextView = new global::Gtk.TextView ();
		this.originalTextView.CanFocus = true;
		this.originalTextView.Name = "originalTextView";
		this.GtkScrolledWindow.Add (this.originalTextView);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w8.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.TreeView = new global::Gtk.TreeView ();
		this.TreeView.CanFocus = true;
		this.TreeView.Name = "TreeView";
		this.GtkScrolledWindow1.Add (this.TreeView);
		this.vbox1.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow1]));
		w10.Position = 3;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 424;
		this.DefaultHeight = 321;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.RunMessagesButton.Clicked += new global::System.EventHandler (this.OnRunMessagesButtonClicked);
		this.RunHTMLDebugButton.Clicked += new global::System.EventHandler (this.OnRunHTMLDebugButtonClicked);
	}
}
